# Generated by Django 4.0.4 on 2022-04-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_finch_toys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='finch',
            name='toys',
        ),
        migrations.DeleteModel(
            name='Toy',
        ),
        migrations.AddField(
            model_name='finch',
            name='studys',
            field=models.ManyToManyField(to='main_app.study'),
        ),
    ]
